[package]
name = "dtls"
version = "0.1.0"
authors = ["Mr.Panda <xivistudios@gmail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"] }
openssl = "0.10.35"
anyhow = "1.0"
bytes = "1"
