[profile.release]
codegen-units = 1
overflow-checks = false
panic = "abort"
opt-level = 3
debug = false
lto = true

[workspace]
members = [
    "service/turn",
    "service/signaling",
    "module/codec",
    "module/trpc",
    "protocol/sdp",
    "protocol/rtp",
    "protocol/srtp",
    "protocol/rtcp",
    "protocol/srtcp",
    "protocol/stun"
]
