wrap_comments = true
format_code_in_doc_comments = true
doc_comment_code_block_width = 100
imports_layout = "Vertical"
match_block_trailing_comma = true
merge_derives = false
imports_granularity = "Crate"
normalize_comments = true
reorder_impl_items = true
reorder_imports = false
reorder_modules = false
struct_lit_single_line = false
tab_spaces = 4
use_field_init_shorthand = true
