[package]
name = "turn-exports"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
tokio = { version = "1.35.0", features = ["rt"] }
turn-rs = { path = "../turn" }
faster-stun = { path = "../stun" }

[lib]
name = "libturn" 
crate-type = ["staticlib"]
