[package]
name = "turn-server"
version = "3.0.0"
edition = "2021"
authors = ["Mr.Panda <xivistudios@gmail.com>"]
description = "A pure rust-implemented turn server."
readme = "../README.md"
homepage = "https://github.com/mycrl/turn-rs"
repository = "https://github.com/mycrl/turn-rs"
license = "GPL-2.0-or-later"
keywords = [
    "stun",
    "webrtc",
    "turn",
    "turn-server"
]

categories = [
    "parsing",
    "network-programming"
]

[dependencies]
ahash = "0.8.3"
async-trait = "0.1"
anyhow = "1.0"
axum = "0.7.5"
bytes = "1.4.0"
clap = { version = "4", features = ["derive", "env"] }
log = "0.4"
mimalloc = { version = "*", default-features = false }
num_cpus = "1.15"
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
stun = { path = "../stun", version = "1" }
simple_logger = "4"
turn = { path = "../turn", version = "1" }
tokio = { version = "1.28.2", features = ["full"] }
toml = "0.7"
tower-http = { version = "0.4", features = ["cors"] }
tower = "0.4"
serde_json = "1.0.117"

[features]
system_allocator = []
