[package]
name = "turn-server"
version = "1.2.0"
edition = "2021"
authors = ["Mr.Panda <xivistudios@gmail.com>"]
description = "A pure rust-implemented turn server."
readme = "../README.md"
homepage = "https://github.com/colourful-rtc/turn-rs"
repository = "https://github.com/colourful-rtc/turn-rs"
license = "GPL-2.0-or-later"
keywords = [
    "stun",
    "webrtc",
    "turn",
    "turn-server"
]

categories = [
    "parsing",
    "network-programming"
]

[dependencies]
bytes = "1.4.0"
bitvec = "1.0"
parking_lot = "0.12"
faster-stun = { path = "../stun", version = "1" }
turn-rs = { path = "../turn", version = "1" }
clap = { version = "4", features = ["derive", "env"] }
tokio = { version = "1.28.2", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.11", features = ["json"] }
tower-http = { version = "0.4", features = ["cors"] }
async-trait = "0.1"
serde_json = "1.0"
simple_logger = "4"
num_cpus = "1.15"
log = "0.4"
anyhow = "1.0"
axum = "0.6"
toml = "0.7"
tower = "0.4"
http = "0.2"
mimalloc = "0.1"
