[net]
bind = "127.0.0.1:3001"

[cluster]
# superiors = "127.0.0.1:3002"
nodes = [
#    "127.0.0.1:3002"
]

[turn]
# bind = "127.0.0.1:3478"

[log]
# log level
#
# An enum representing the available verbosity levels of the logger.
level = "info"
