[package]
name = "trpc"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
async-trait = "0.1.52"
async-nats = "0.9.9"
serde_json = "1.0.61"
anyhow = "1.0"
