name: docker build and
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: "docker version to release"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GithubPackages
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          file: Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: quasipaa/turn-server:${{github.event.inputs.version}}, quasipaa/turn-server:latest