name: publish release
on:
    create:
        tags:
            - 'v*'
jobs:
    build:
        runs-on: '${{ matrix.os }}'
        strategy:
            matrix:
                os:
                    - ubuntu-latest
                    - windows-latest
        steps:
            -
                uses: actions/checkout@v4
            -
                uses: actions/cache@v3
                with:
                    path: |
                        ~/.cargo/bin/
                        ~/.cargo/registry/index/
                        ~/.cargo/registry/cache/
                        ~/.cargo/git/db/
                        target/
                    key: '${{ runner.os }}-cargo-${{ hashFiles(''**/Cargo.lock'') }}'
            -
                name: Build release (Linux)
                if: runner.os == 'Linux'
                run: |
                    sudo apt update
                    sudo apt install -y protobuf-compiler libprotobuf-dev
                    cargo build --release
            -
                name: Build release (Windows)
                if: runner.os == 'Windows'
                run: |
                    mkdir third_party;
                    Invoke-WebRequest -Uri https://github.com/protocolbuffers/protobuf/releases/download/v25.1/protoc-25.1-win64.zip -OutFile ./third_party/protoc-25.1-win64.zip;
                    Expand-Archive -Path ./third_party/protoc-25.1-win64.zip -DestinationPath ./third_party;
                    $currentDirectory = $PWD.Path;
                    $env:PATH += ";$currentDirectory/third_party/bin";
                    cargo build --release;
            -
                name: Rename release (Linux)
                if: runner.os == 'Linux'
                run: |
                    mv ./target/release/turn-balance-server ./target/release/turn-balance-server-linux-x86_64
                    mv ./target/release/turn-server ./target/release/turn-server-linux-x86_64
                    mv ./target/release/turn-cli ./target/release/turn-cli-linux-x86_64
            -
                name: Upload artifact (Linux)
                if: runner.os == 'Linux'
                uses: actions/upload-artifact@v3
                with:
                    name: linux-x86_64
                    path: |
                        ./target/release/turn-balance-server-linux-x86_64
                        ./target/release/turn-server-linux-x86_64
                        ./target/release/turn-cli-linux-x86_64
            -
                name: Rename release (Windows)
                if: runner.os == 'Windows'
                run: |
                    Remove-Item -Path "./target/release/turn-balance-server-windows-x86_64.exe" -ErrorAction SilentlyContinue; 
                    Remove-Item -Path "./target/release/turn-server-windows-x86_64.exe" -ErrorAction SilentlyContinue; 
                    Remove-Item -Path "./target/release/turn-cli-windows-x86_64.exe" -ErrorAction SilentlyContinue; 
                    Rename-Item -Path "./target/release/turn-balance-server.exe" -NewName "turn-balance-server-windows-x86_64.exe";
                    Rename-Item -Path "./target/release/turn-server.exe" -NewName "turn-server-windows-x86_64.exe";
                    Rename-Item -Path "./target/release/turn-cli.exe" -NewName "turn-cli-windows-x86_64.exe";
            -
                name: Upload artifact (Windows)
                if: runner.os == 'Windows'
                uses: actions/upload-artifact@v3
                with:
                    name: windows-x86_64
                    path: |
                        ./target/release/turn-balance-server-windows-x86_64.exe
                        ./target/release/turn-server-windows-x86_64.exe
                        ./target/release/turn-cli-windows-x86_64.exe
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout code
                uses: actions/checkout@v3
            -
                name: Download All Artifacts
                uses: actions/download-artifact@v3
                with:
                    path: artifacts
            -
                name: Create release
                id: create_release
                uses: softprops/action-gh-release@v1
                env:
                    GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
                with:
                    tag_name: ${{ github.ref_name }}
                    name: ${{ github.ref_name }}
                    draft: false
                    prerelease: false
                    files: artifacts/**/*