name: tests
on:
    push:
        branches:
            - main
        paths:
            - cli/**
            - tests/**
            - stun/**
            - turn/**
            - turn-server/**
            - turn-balance/**
            - Cargo.toml
            - Cargo.lock
            - protos/**
    pull_request:
        branches:
            - main
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/cache@v3
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      target/
                  key: "${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}"
            - name: Run tests
              run: cargo test
